### ISSUE TITLE
Desabilitar obrigatoriedade CPF, CNPJ, Razão Social

### ISSUE THREAD

**Issue by LuizSantos1** [rafaelstz/magento1-validaCPF#1]
@rafaelstz Tudo bem?
Desculpe por te contatar dessa forma, não consegui de outras já que o
probleminha é mais chato.

Estou usando o módulo One Step Checkout do Elisei, no entanto,
tomei um strike do Google Ads porque os campos CPF, CNPJ, Razão Social e Data de Aniversário
estão como "obrigatórios", e depois da LGPD, o Google disse que eles devem ser opcionais.

Pedi ao elisei e ele não quis modifica e nem falar onde poderia modificar essa obrigatoriedade.
E já desabilitei no backend mas não funciona.

Você poderia me ajudar? 
Este é o link do módulo: https://github.com/elisei/moip-transparente-magento

Desde já, fica aqui meu agradecimento.

**Comment by rafaelstz** [comment]
Olá @LuizSantos1,

Faz tempo que não utilizo esse módulo mas você consegue colocar o taxvat via admin como opcional que no módulo é o CPF, e para o CNPJ esse abaixo é o arquivo que cria o campo.

https://github.com/elisei/moip-transparente-magento/blob/master/app/design/frontend/base/default/template/MOIP/onestepcheckout/customer/tipopessoa.phtml

**Comment by LuizSantos1** [comment]
@rafaelstz 
Eu já fiz o procedimento de desabilitar no admin panel, não funciona. Segue como obrigatório.
Esse módulo deve ter algum tipo de validação em JS, porque eu consegui retirar o asterisco, a mensagem
"Esse campo é obrigatório", já rodei uma SQL query pra mudar o "is Required" para "O", e ainda assim,
ao clicar em ir para próximo, que é a página de pagamento em si, ele faz o refresh, mas volta para a página de criar cliente. 

Ou seja, o módulo seguramente detecta que esses campos estão vazios e por isso a conta não consegue ser criada.

No Checkout da IWD Checkout Suite, o único que faltaria é o campo telefone, que também já fiz de
tudo, mas segue como obrigatório.
